/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package vista;

/**
 *
 * @author PC_TONY
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        mnuUsuario = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        mnuVenta = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        mnuRproducto = new javax.swing.JMenuItem();
        mnuListaprodu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC_TONY\\Desktop\\fondoazul.jpg")); // NOI18N
        desktopPane.add(jLabel1);
        jLabel1.setBounds(0, 0, 820, 470);

        fileMenu.setBackground(new java.awt.Color(0, 204, 255));
        fileMenu.setForeground(new java.awt.Color(0, 0, 0));
        fileMenu.setMnemonic('f');
        fileMenu.setText("Registro");

        mnuUsuario.setMnemonic('o');
        mnuUsuario.setText("Registo Usuario");
        fileMenu.add(mnuUsuario);

        menuBar.add(fileMenu);

        editMenu.setBackground(new java.awt.Color(0, 204, 255));
        editMenu.setForeground(new java.awt.Color(0, 0, 0));
        editMenu.setMnemonic('e');
        editMenu.setText("Venta");

        mnuVenta.setMnemonic('t');
        mnuVenta.setText("Realizar Venta");
        editMenu.add(mnuVenta);

        menuBar.add(editMenu);

        helpMenu.setBackground(new java.awt.Color(0, 204, 255));
        helpMenu.setForeground(new java.awt.Color(0, 0, 0));
        helpMenu.setMnemonic('h');
        helpMenu.setText("Productos");

        mnuRproducto.setMnemonic('c');
        mnuRproducto.setText("Registrar Producto");
        helpMenu.add(mnuRproducto);

        mnuListaprodu.setMnemonic('a');
        mnuListaprodu.setText("Lista de Productos");
        helpMenu.add(mnuListaprodu);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 814, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem mnuListaprodu;
    private javax.swing.JMenuItem mnuRproducto;
    private javax.swing.JMenuItem mnuUsuario;
    private javax.swing.JMenuItem mnuVenta;
    // End of variables declaration//GEN-END:variables

}
