/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Color;
import modelo.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Carlos
 */
public class FrmProducto extends javax.swing.JFrame {

    /**
     * Creates new form FrmProductor
     */
    public FrmProducto() {
        initComponents();
        verProducto();
        habilitarBotones(false, false, false);
        setLocationRelativeTo(null);
    }

    void limpiar(){
        txtidProducto.setText("");
        txtnombreProd.setText("");
        txtdescripcionprod.setText("");
        txtprecioprod.setText("");
        txtstock.setText("");
        txtmedidas.setText("");
        txtidProducto.requestFocus();
    }
    
    void verProducto(){
        DefaultTableModel modeloproducto;
        DAOProducto oDProd = new DAOProducto();
        modeloproducto = oDProd.verProducto();
        tblproducto.setModel(modeloproducto);  
    }
    
    void habilitarBotones(boolean a,boolean e,boolean el){
        btnAgregar.setEnabled(a);
        btnEditar.setEnabled(e);
        btnEliminar.setEnabled(el); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtidProducto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtnombreProd = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtdescripcionprod = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtprecioprod = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtstock = new javax.swing.JTextField();
        txtmedidas = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblproducto = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(64, 133, 225));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("ID Producto: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));
        getContentPane().add(txtidProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 70, 30));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("Nombre Producto :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, 30));

        txtnombreProd.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        getContentPane().add(txtnombreProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 390, 30));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setText("Descripción :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, 30));

        txtdescripcionprod.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        getContentPane().add(txtdescripcionprod, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 390, 30));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("Precio Unitario :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 150, 30));

        txtprecioprod.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        getContentPane().add(txtprecioprod, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 120, 30));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setText("Stock :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, -1, 30));

        txtstock.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        getContentPane().add(txtstock, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, 80, 30));

        txtmedidas.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtmedidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmedidasActionPerformed(evt);
            }
        });
        getContentPane().add(txtmedidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 120, 30));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setText("Medidas :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, -1, 30));

        btnAgregar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/guardar.png"))); // NOI18N
        btnAgregar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregarMouseExited(evt);
            }
        });
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 70, 40));

        tblproducto.setBackground(new java.awt.Color(255, 204, 102));
        tblproducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre Producto", "Descripcion", "Precio Unitario", "Stock", "Medidas"
            }
        ));
        tblproducto.setSelectionBackground(new java.awt.Color(0, 204, 255));
        tblproducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblproductoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblproducto);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 846, 190));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("REGISTRO DE PRODUCTOS");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 340, 50));

        btnEditar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editar.png"))); // NOI18N
        btnEditar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditarMouseExited(evt);
            }
        });
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 70, 40));

        btnEliminar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/borrar.png"))); // NOI18N
        btnEliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarMouseExited(evt);
            }
        });
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 70, 40));

        btnSalir.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cerrar-sesion-chico.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalirMouseExited(evt);
            }
        });
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 310, 120, 50));

        btnNuevo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nueva-pagina.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.setAlignmentX(1.0F);
        btnNuevo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNuevoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNuevoMouseExited(evt);
            }
        });
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 250, 120, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo bl.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        String nombreProd,descripcionprod;
        int stock,idProducto;
        double precioprod,medidas;
        
        idProducto = Integer.parseInt(txtidProducto.getText());
        nombreProd = txtnombreProd.getText();
        descripcionprod = txtdescripcionprod.getText();
        precioprod = Double.parseDouble(txtprecioprod.getText());
        stock = Integer.parseInt(txtstock.getText());
        medidas = Double.parseDouble(txtmedidas.getText());
        
        DTOProducto oProd= new DTOProducto();
        oProd.setIdProducto(idProducto);
        oProd.setNombreProd(nombreProd);
        oProd.setDescripcionprod(descripcionprod);
        oProd.setPrecioprod(precioprod);
        oProd.setStock(stock);
        oProd.setMedidas(medidas);
        
        DAOProducto oDProd=new DAOProducto();
        oDProd.editarProducto(oProd);
        
        verProducto();
        limpiar();
        habilitarBotones(false, false, false);

    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        String nombreProd,descripcionprod;
        int stock,idProducto;
        double precioprod,medidas;
        
        idProducto = Integer.parseInt(txtidProducto.getText());
        nombreProd = txtnombreProd.getText();
        descripcionprod = txtdescripcionprod.getText();
        precioprod = Double.parseDouble(txtprecioprod.getText());
        stock = Integer.parseInt(txtstock.getText());
        medidas = Double.parseDouble(txtmedidas.getText());
        
        DTOProducto oProd= new DTOProducto();
        oProd.setIdProducto(idProducto);
        oProd.setNombreProd(nombreProd);
        oProd.setDescripcionprod(descripcionprod);
        oProd.setPrecioprod(precioprod);
        oProd.setStock(stock);
        oProd.setMedidas(medidas);
        
        DAOProducto oDProd=new DAOProducto();
        oDProd.agregarProducto(oProd);
        
        verProducto();
        limpiar();
        habilitarBotones(false, false, false);

    }//GEN-LAST:event_btnAgregarActionPerformed

    private void tblproductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblproductoMouseClicked
        int fila;
        fila = tblproducto.getSelectedRow();
        String id,nombre,descripcion,precio,stock,medidas;
        id = (String) tblproducto.getValueAt(fila,0);
        nombre = (String) tblproducto.getValueAt(fila,1);
        descripcion = (String) tblproducto.getValueAt(fila,2);
        precio = (String) tblproducto.getValueAt(fila,3);
        stock = (String) tblproducto.getValueAt(fila,4);
        medidas = (String) tblproducto.getValueAt(fila,5);
        
        txtidProducto.setText(id);
        txtnombreProd.setText(nombre);
        txtdescripcionprod.setText(descripcion);
        txtprecioprod.setText(precio);
        txtstock.setText(stock);
        txtmedidas.setText(medidas);
        habilitarBotones(false, true, true);

    }//GEN-LAST:event_tblproductoMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int idProducto;
        idProducto = Integer.parseInt(txtidProducto.getText());
        
        DTOProducto oProd =new DTOProducto(idProducto);
        
        DAOProducto oDProd=new DAOProducto();
        oDProd.eliminarProducto(oProd);
        
        verProducto();
        limpiar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        limpiar();
        habilitarBotones(true, false, false);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnAgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseEntered
        btnAgregar.setBackground(new Color(249, 162, 28 ));
    }//GEN-LAST:event_btnAgregarMouseEntered

    private void btnAgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseExited
        btnAgregar.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnAgregarMouseExited

    private void btnEditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseEntered
        btnEditar.setBackground(new Color(249, 162, 28 ));
    }//GEN-LAST:event_btnEditarMouseEntered

    private void btnEditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseExited
        btnEditar.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnEditarMouseExited

    private void btnEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseEntered
        btnEliminar.setBackground(new Color(249, 162, 28 ));
    }//GEN-LAST:event_btnEliminarMouseEntered

    private void btnEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseExited
        btnEliminar.setBackground(new Color(255,255,255 ));
    }//GEN-LAST:event_btnEliminarMouseExited

    private void btnNuevoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoMouseEntered
        btnNuevo.setBackground(new Color(249, 162, 28 ));
    }//GEN-LAST:event_btnNuevoMouseEntered

    private void btnNuevoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoMouseExited
        btnNuevo.setBackground(new Color(255,255,255 ));
    }//GEN-LAST:event_btnNuevoMouseExited

    private void btnSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseEntered
        btnSalir.setBackground(new Color(249, 162, 28 ));
    }//GEN-LAST:event_btnSalirMouseEntered

    private void btnSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseExited
        btnSalir.setBackground(new Color(255,255,255 ));
    }//GEN-LAST:event_btnSalirMouseExited

    private void txtmedidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmedidasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmedidasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblproducto;
    private javax.swing.JTextField txtdescripcionprod;
    private javax.swing.JTextField txtidProducto;
    private javax.swing.JTextField txtmedidas;
    private javax.swing.JTextField txtnombreProd;
    private javax.swing.JTextField txtprecioprod;
    private javax.swing.JTextField txtstock;
    // End of variables declaration//GEN-END:variables
}
