/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import modelo.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Carlos
 */
public class FrmProducto extends javax.swing.JFrame {

    /**
     * Creates new form FrmProductor
     */
    public FrmProducto() {
        initComponents();
        verProducto();
        habilitarBotones(false, false, false);
    }

    void limpiar(){
        txtidProducto.setText("");
        txtnombreProd.setText("");
        txtdescripcionprod.setText("");
        txtprecioprod.setText("");
        txtstock.setText("");
        txtmedidas.setText("");
        txtidProducto.requestFocus();
    }
    
    void verProducto(){
        DefaultTableModel modeloproducto;
        DAOProducto oDProd = new DAOProducto();
        modeloproducto = oDProd.verProducto();
        tblproducto.setModel(modeloproducto);  
    }
    
    void habilitarBotones(boolean a,boolean e,boolean el){
        btnAgregar.setEnabled(a);
        btnEditar.setEnabled(e);
        btnEliminar.setEnabled(el); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtidProducto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtnombreProd = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtdescripcionprod = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtprecioprod = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtstock = new javax.swing.JTextField();
        txtmedidas = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblproducto = new javax.swing.JTable();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(64, 133, 225));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID Producto: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 19, -1, -1));
        getContentPane().add(txtidProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 19, 60, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nombre Producto :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 78, -1, 30));

        txtnombreProd.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        getContentPane().add(txtnombreProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 78, 390, 30));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Descripción :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 128, -1, 30));

        txtdescripcionprod.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        getContentPane().add(txtdescripcionprod, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 128, 390, 30));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Precio Unitario :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 178, -1, 30));
        getContentPane().add(txtprecioprod, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 178, 120, 30));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Stock :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 214, -1, 30));

        txtstock.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        getContentPane().add(txtstock, new org.netbeans.lib.awtextra.AbsoluteConstraints(539, 217, 120, -1));

        txtmedidas.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        getContentPane().add(txtmedidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 216, 120, 30));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Medidas :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 214, -1, 30));

        btnAgregar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 272, 110, 50));

        tblproducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre Producto", "Descripcion", "Precio Unitario", "Stock", "Medidas"
            }
        ));
        tblproducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblproductoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblproducto);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 340, 846, 190));

        btnEditar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 272, 110, 50));

        btnEliminar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 272, 110, 50));

        btnSalir.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 272, 110, 50));

        btnNuevo.setText("Nuevo");
        btnNuevo.setAlignmentX(1.0F);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 70, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/fondo2.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 900, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        String nombreProd,descripcionprod;
        int stock,idProducto;
        double precioprod,medidas;
        
        idProducto = Integer.parseInt(txtidProducto.getText());
        nombreProd = txtnombreProd.getText();
        descripcionprod = txtdescripcionprod.getText();
        precioprod = Double.parseDouble(txtprecioprod.getText());
        stock = Integer.parseInt(txtstock.getText());
        medidas = Double.parseDouble(txtmedidas.getText());
        
        DTOProducto oProd= new DTOProducto();
        oProd.setIdProducto(idProducto);
        oProd.setNombreProd(nombreProd);
        oProd.setDescripcionprod(descripcionprod);
        oProd.setPrecioprod(precioprod);
        oProd.setStock(stock);
        oProd.setMedidas(medidas);
        
        DAOProducto oDProd=new DAOProducto();
        oDProd.editarProducto(oProd);
        
        verProducto();
        limpiar();
        habilitarBotones(false, false, false);

    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        String nombreProd,descripcionprod;
        int stock,idProducto;
        double precioprod,medidas;
        
        idProducto = Integer.parseInt(txtidProducto.getText());
        nombreProd = txtnombreProd.getText();
        descripcionprod = txtdescripcionprod.getText();
        precioprod = Double.parseDouble(txtprecioprod.getText());
        stock = Integer.parseInt(txtstock.getText());
        medidas = Double.parseDouble(txtmedidas.getText());
        
        DTOProducto oProd= new DTOProducto();
        oProd.setIdProducto(idProducto);
        oProd.setNombreProd(nombreProd);
        oProd.setDescripcionprod(descripcionprod);
        oProd.setPrecioprod(precioprod);
        oProd.setStock(stock);
        oProd.setMedidas(medidas);
        
        DAOProducto oDProd=new DAOProducto();
        oDProd.agregarProducto(oProd);
        
        verProducto();
        limpiar();
        habilitarBotones(false, false, false);

    }//GEN-LAST:event_btnAgregarActionPerformed

    private void tblproductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblproductoMouseClicked
        int fila;
        fila = tblproducto.getSelectedRow();
        String id,nombre,descripcion,precio,stock,medidas;
        id = (String) tblproducto.getValueAt(fila,0);
        nombre = (String) tblproducto.getValueAt(fila,1);
        descripcion = (String) tblproducto.getValueAt(fila,2);
        precio = (String) tblproducto.getValueAt(fila,3);
        stock = (String) tblproducto.getValueAt(fila,4);
        medidas = (String) tblproducto.getValueAt(fila,5);
        
        txtidProducto.setText(id);
        txtnombreProd.setText(nombre);
        txtdescripcionprod.setText(descripcion);
        txtprecioprod.setText(precio);
        txtstock.setText(stock);
        txtmedidas.setText(medidas);
        habilitarBotones(false, true, true);

    }//GEN-LAST:event_tblproductoMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int idProducto;
        idProducto = Integer.parseInt(txtidProducto.getText());
        
        DTOProducto oProd =new DTOProducto(idProducto);
        
        DAOProducto oDProd=new DAOProducto();
        oDProd.eliminarProducto(oProd);
        
        verProducto();
        limpiar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        limpiar();
        habilitarBotones(true, false, false);
    }//GEN-LAST:event_btnNuevoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblproducto;
    private javax.swing.JTextField txtdescripcionprod;
    private javax.swing.JTextField txtidProducto;
    private javax.swing.JTextField txtmedidas;
    private javax.swing.JTextField txtnombreProd;
    private javax.swing.JTextField txtprecioprod;
    private javax.swing.JTextField txtstock;
    // End of variables declaration//GEN-END:variables
}
