/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import java.awt.Color;

/**
 *
 * @author PC_TONY
 */
public class ListaVentas extends javax.swing.JPanel {

    /**
     * Creates new form RegistrodeVentas
     */
    public ListaVentas() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtDocumento = new javax.swing.JTextField();
        btnBuscarDoc = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        txtFecha = new javax.swing.JTextField();
        btnBuscarFecha = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("Listado de Ventas");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 210, 50));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Fecha Emision", "N° Documento", "RUC o DNI", "Nombre Empresa", "TOTAL"
            }
        ));
        jTable1.setSelectionBackground(new java.awt.Color(0, 204, 255));
        jTable1.setUpdateSelectionOnSort(false);
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 680, 200));
        add(txtDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 140, 30));

        btnBuscarDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lupa.png"))); // NOI18N
        btnBuscarDoc.setText("Buscar");
        btnBuscarDoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarDocMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarDocMouseExited(evt);
            }
        });
        add(btnBuscarDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 100, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("N° Documento(RUC/DNI) :");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 180, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Fecha:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, 30));

        jCalendar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jCalendar1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        add(jCalendar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, -1, -1));
        add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 140, 30));

        btnBuscarFecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lupa.png"))); // NOI18N
        btnBuscarFecha.setText("Buscar");
        btnBuscarFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarFechaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarFechaMouseExited(evt);
            }
        });
        add(btnBuscarFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 100, 30));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo bl.jpg"))); // NOI18N
        add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 732, 616));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarDocMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarDocMouseEntered
        btnBuscarDoc.setBackground(new Color(201, 253, 126));
    }//GEN-LAST:event_btnBuscarDocMouseEntered

    private void btnBuscarDocMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarDocMouseExited
        btnBuscarDoc.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnBuscarDocMouseExited

    private void btnBuscarFechaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarFechaMouseEntered
        btnBuscarFecha.setBackground(new Color(201, 253, 126));
    }//GEN-LAST:event_btnBuscarFechaMouseEntered

    private void btnBuscarFechaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarFechaMouseExited
        btnBuscarFecha.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnBuscarFechaMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton btnBuscarDoc;
    private javax.swing.JButton btnBuscarFecha;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JTextField txtFecha;
    // End of variables declaration//GEN-END:variables
}
