/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package vista;

/**
 *
 * @author PC_TONY
 */
public class PrincipalForm extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public PrincipalForm() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        btnSalir = new javax.swing.JButton();
        btnIngresar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        opCargarUsuario = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        opCargarVenta = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        opCargarRegistro = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        desktopPane.add(btnSalir);
        btnSalir.setBounds(410, 260, 100, 40);

        btnIngresar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnIngresar.setText("LOGIN");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        desktopPane.add(btnIngresar);
        btnIngresar.setBounds(280, 260, 100, 40);

        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jTextField1.setText("BIENVENIDO");
        desktopPane.add(jTextField1);
        jTextField1.setBounds(320, 120, 160, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC_TONY\\Desktop\\fondoazul.jpg")); // NOI18N
        desktopPane.add(jLabel1);
        jLabel1.setBounds(0, 0, 820, 470);

        fileMenu.setBackground(new java.awt.Color(0, 204, 255));
        fileMenu.setMnemonic('f');
        fileMenu.setText("Registro");

        opCargarUsuario.setMnemonic('o');
        opCargarUsuario.setText("Registo Usuario");
        opCargarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opCargarUsuarioActionPerformed(evt);
            }
        });
        fileMenu.add(opCargarUsuario);

        menuBar.add(fileMenu);

        editMenu.setBackground(new java.awt.Color(0, 204, 255));
        editMenu.setMnemonic('e');
        editMenu.setText("Venta");
        editMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editMenuActionPerformed(evt);
            }
        });

        opCargarVenta.setMnemonic('t');
        opCargarVenta.setText("Realizar Venta");
        opCargarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opCargarVentaActionPerformed(evt);
            }
        });
        editMenu.add(opCargarVenta);

        menuBar.add(editMenu);

        helpMenu.setBackground(new java.awt.Color(0, 204, 255));
        helpMenu.setMnemonic('h');
        helpMenu.setText("Productos");

        opCargarRegistro.setMnemonic('c');
        opCargarRegistro.setText("Registrar Producto");
        opCargarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opCargarRegistroActionPerformed(evt);
            }
        });
        helpMenu.add(opCargarRegistro);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 814, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opCargarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opCargarVentaActionPerformed
        new VentaForm().setVisible(true);
    }//GEN-LAST:event_opCargarVentaActionPerformed

    private void editMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editMenuActionPerformed
        
    }//GEN-LAST:event_editMenuActionPerformed

    private void opCargarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opCargarUsuarioActionPerformed
        new RegistrarUsuario().setVisible(true);
    }//GEN-LAST:event_opCargarUsuarioActionPerformed

    private void opCargarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opCargarRegistroActionPerformed
        FrmProducto frmProducto = new FrmProducto();
        frmProducto.setVisible(true);
    }//GEN-LAST:event_opCargarRegistroActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        new UsuarioForm().setVisible(true);
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem opCargarRegistro;
    private javax.swing.JMenuItem opCargarUsuario;
    private javax.swing.JMenuItem opCargarVenta;
    // End of variables declaration//GEN-END:variables

    private static class Product {

        public Product() {
        }

        private Product(PrincipalForm aThis, boolean b) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        private void SetVisible(boolean b) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }
    }

}
