/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import modelo.DAOUsuario;
import modelo.DTOUsuario;

/**
 *
 * @author PC_TONY
 */
public class UsuarioForm extends javax.swing.JFrame {

    /**
     * Creates new form UsuarioForm
     */
    public UsuarioForm() {
        initComponents();
        setLocationRelativeTo(null);
    }

    void limpiar() {
        txtUsuario.setText("");
        txtContra.setText("");
        txtUsuario.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnSalirlogin = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        btnIngresarlogin = new javax.swing.JButton();
        txtContra = new javax.swing.JPasswordField();
        txtUsuario = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(720, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Usuario:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Contraseña:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/entrar.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 390, 30, 60));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cerrar-sesion-chico.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 470, 30, 60));

        btnSalirlogin.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSalirlogin.setText("SALIR");
        btnSalirlogin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalirlogin.setPreferredSize(new java.awt.Dimension(84, 27));
        btnSalirlogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirloginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalirloginMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSalirloginMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnSalirloginMouseReleased(evt);
            }
        });
        btnSalirlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirloginActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalirlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 470, 150, 60));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("No tengo una cuenta");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel12MouseExited(evt);
            }
        });
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 560, -1, -1));

        btnIngresarlogin.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnIngresarlogin.setText("INGRESAR");
        btnIngresarlogin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnIngresarlogin.setRequestFocusEnabled(false);
        btnIngresarlogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIngresarloginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIngresarloginMouseExited(evt);
            }
        });
        btnIngresarlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarloginActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresarlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 390, 150, 60));

        txtContra.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtContra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtContra.setBorder(new javax.swing.border.MatteBorder(null));
        txtContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraActionPerformed(evt);
            }
        });
        txtContra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtContraKeyPressed(evt);
            }
        });
        getContentPane().add(txtContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, 250, 40));

        txtUsuario.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsuario.setBorder(new javax.swing.border.MatteBorder(null));
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyPressed(evt);
            }
        });
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, 250, 40));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tornillo.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, 90, 70));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tuerca (1).png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 90, 80));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/llave.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 500, -1, 90));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/usuario b.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 130, 150));

        jLabel2.setBackground(new java.awt.Color(250, 250, 250));
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 360, 580));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LOGO_HERRAVENTURA.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 360, 280));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FONDITO.jpg"))); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarloginActionPerformed
        String user, password;

        user = txtUsuario.getText();
        password = txtContra.getText();

        DTOUsuario objeto = new DTOUsuario();
        objeto.setNombreUsu(user);
        objeto.setContrasenaUsu(password);

        DAOUsuario objetoD = new DAOUsuario();

        if (objetoD.verificarCredenciales(objeto)) {
            // Credenciales válidas
            

            PrincipalForm ventanaPrincipal = new PrincipalForm();
            ventanaPrincipal.setVisible(true);

            this.dispose();
        } else {
            // Credenciales inválidas
            JOptionPane.showMessageDialog(null, "Credenciales incorrectas. Inicio de sesión fallido.", "Error", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_btnIngresarloginActionPerformed

    private void btnSalirloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirloginActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirloginActionPerformed

    private void txtContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraActionPerformed

    private void btnSalirloginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirloginMousePressed

    }//GEN-LAST:event_btnSalirloginMousePressed

    private void btnSalirloginMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirloginMouseReleased

    }//GEN-LAST:event_btnSalirloginMouseReleased

    private void btnSalirloginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirloginMouseEntered
        btnSalirlogin.setBackground(new Color(255, 69, 69));
    }//GEN-LAST:event_btnSalirloginMouseEntered

    private void btnSalirloginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirloginMouseExited
        btnSalirlogin.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnSalirloginMouseExited

    private void btnIngresarloginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarloginMouseEntered
        btnIngresarlogin.setBackground(new Color(28, 182, 249  ));
    }//GEN-LAST:event_btnIngresarloginMouseEntered

    private void btnIngresarloginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarloginMouseExited
        btnIngresarlogin.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnIngresarloginMouseExited

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        new RegistrarUsuario().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseEntered
        jLabel12.setForeground(Color.BLUE);
    }//GEN-LAST:event_jLabel12MouseEntered

    private void jLabel12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseExited
        jLabel12.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabel12MouseExited

    private void txtUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnIngresarloginActionPerformed(null);
        }
    }//GEN-LAST:event_txtUsuarioKeyPressed

    private void txtContraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContraKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnIngresarloginActionPerformed(null);
        }
    }//GEN-LAST:event_txtContraKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsuarioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsuarioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsuarioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsuarioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsuarioForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresarlogin;
    private javax.swing.JButton btnSalirlogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField txtContra;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
